:deckjs_theme: swiss
= AsciiDoc et sa suite logicielle
Sébastien Nicaisse

== Qu'est-ce qu'asciiDoc ? (1/2)

[%step]
* Un format de document créé en 2002 par Stuart Rackham (la http://www.methods.co.nz/asciidoc/userguide.html[spec^]).

[%step]
* Il est... 

- *Simple* : un format plat en mode text.

- *Efficace* : permet au rédacteur de se focaliser uniquement sur le contenu.

- *Populaire* : Un outil de génération de documentation (http://gist.asciidoctor.org/[DocGists^]) pour les utilisateurs Github. 

- *Puissant* : Possibilité de générer un grand nombre de formats fichiers (HTML5, PDF, LATEX, etc...).

- *Extensible* : De nombreuses extensions existes (https://github.com/asciidoctor/asciidoctor-deck.js[asciidoctor-deck^], https://github.com/asciidoctor/asciidoctor-diagram[asciidoctor-diagram^] ...). 

== Qu'est-ce qu'asciiDoc ? (2/2)

[ditaa]
----
                  +-----------+
                  |  Template |
                  |  AsciiDoc |
                  |  cRED {d} |
                  +-----+-----+
                        |
                        |
                        v                          
+----------+    +---------------+           +---------------------------+
| Fichier  |    |               | genere    |                           |
| AsciiDoc +--->|   AsciiDoc    +---------> |      Fichier              |
| (.adoc)  |    | Preprocesseur |           | HTML5 ou PDF ou LATEX ... |
| cGRE  {d}|    |    cPNK       |           |         cBLU     {d}      |
+----------+    +---------------+           +---------------------------+
                       ^
                       |
                       |
                  +----+------+
                  |   Style   |
                  |  AsciiDoc |
                  |  cYEL {d} |
                  +-----+-----+

----

== asciiDoc Syntax (1/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#paragraphs" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (2/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#formatted-text" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (3/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#document-header" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (4/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#section-titles" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (5/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#include-files" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (6/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#horizontal-rules-and-page-breaks" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (7/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#lists" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (8/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#images" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (9/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#videos" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (10/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#source-code" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (11/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#more-delimited-blocks" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (12/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#block-id-role-and-options" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (13/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#comments" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (14/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#tables" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (15/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#ui-macros" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (16/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#attributes-and-substitutions" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (17/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#text-replacement" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (18/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#escaping-text" frameBorder="0" width=100% height=600px></iframe>

++++

== asciiDoc Syntax (19/19)

++++

<iframe src="http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#bibliography" frameBorder="0" width=100% height=600px></iframe>

++++



== Diagram generation (ditaa)

[ditaa]
----
                   +-------------+
                   | asciidoctor |-------+
                   |  diagram    |       |
                   +-------------+       | png out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ asciidoctor +--> |               |
 |  Text  |   +-------------+    |Beatiful output|
 |Document|   |   !magic!   |    |               |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
----

[source]
----
"
                   +-------------+
                   | asciidoctor |-------+
                   |  diagram    |       |
                   +-------------+       | png out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ asciidoctor +--> |               |
 |  Text  |   +-------------+    |Beatiful output|
 |Document|   |   !magic!   |    |               |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
"
----

== Diagram generation (PlanUML)

[plantuml, diagram-classes, png]     
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....

[source]     
....
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
....

== Diagram generation (Graphviz)

[graphviz, dot-example, svg]
----
digraph g {
    a -> b
    b -> c
    c -> d
    d -> a
}
----

[source]
----
digraph g {
    a -> b
    b -> c
    c -> d
    d -> a
}
----

== D'autres extensions

* https://github.com/domgold/asciidoctor-gherkin-extension[asciidoctor-gherkin-extension^] 

* http://fix.github.io/asciidoctor-screenshot/[Asciidocshot^]

* https://github.com/allati/asciidoctor-extension-monotree[asciidoctor-extension-monotree^]

* https://github.com/asciidoctor/asciidoctor-latex[asciidoctor-latex^]

* http://asciidoctor.org/docs/asciidoctor-diagram/[asciidoctor-diagram^]

* https://github.com/asciidoctor/asciidoctor-deck.js[asciidoctor-deck.js^]

== Les principaux outils

=== Compilateurs

* http://www.methods.co.nz/asciidoc/manpage.html[asciidoc^]

* http://asciidoctor.org/[asciidoctor^]

=== Plugins de génération de la documentation du code source

* https://github.com/asciidoctor/asciidoclet[asciidoclet^]

* https://github.com/asciidoctor/asciidoctor-grunt-plugin[plugin grunt^]

=== Plugins des outils de gestions de dépendances

* https://github.com/asciidoctor/asciidoctor-maven-examples[maven^]

* https://github.com/asciidoctor/asciidoctor-gradle-plugin[gradle^]

=== Plugins IDE

* https://github.com/maxandersen/jbosstools-asciidoctor[eclipse^]

* https://github.com/asciidoctor/asciidoctor-intellij-plugin[intellij^]

=== Plugins navigateur

* https://github.com/asciidoctor/asciidoctor-firefox-addon[firefox^]

* https://github.com/asciidoctor/asciidoctor-chrome-extension[chrome^]

== Demo

[source]

----
sudo asciidoctor -T /home/soyn7401/Modèles/asciidoctor-deck.js-master/templates/haml -r asciidoctor-diagram -o /var/www/html/asciiDocPres/asciiDocPres.html /data/workspace/Doc/asciidoc/asciiDocPres.adoc
----
